# Generated by Django 4.2.6 on 2025-12-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SOLD', 'Sold Out')], default='PENDING', max_length=10),
        ),
    ]
