# Generated by Django 5.2.9 on 2025-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_seller_name",
            field=models.BooleanField(
                default=True, help_text="Show seller name in product details"
            ),
        ),
    ]
