# Generated by Django 4.2.6 on 2025-12-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_name',
            field=models.BooleanField(default=False),
        ),
    ]
